FROM golang:1.16-alpine
WORKDIR /
COPY go.mod go.sum ./
RUN go mod download
COPY . . 
ENV RABBIT_HOST 192.168.1.10
ENV HOSTIP_MONGO 192.168.1.10
RUN go build -o goRabbitSubscriber
CMD ["/goRabbitSubscriber"]